[workspace]
members = [
    "crates/cli",
    "crates/gui/src-tauri",
    "crates/core",
    "crates/danmu",
    "crates/marcos",
    "crates/status",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
