[workspace]
members = ["seam", "seam_core", "seam_core_marcos", "seam_danmu", "seam_status"]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
