# 播放器路径或命令
[play]
bin = "mpv"
# 播放器参数
args = []

[headers.global]
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.200"
# 各平台
[headers.douyin]
cookie = "xxxx"

[headers.ks]
cookie = "xxxx"


# [rid]: 房间号
# [title]: 标题
# [time]: 时间戳
# [date]: 日期
[file_name]
# 录制文件标题
video = "[rid]-[title]-[date]-[time]"
# danmu文件标题
danmu = "[rid]-[title]-[date]-[time]"
