# [rid]: 房间号
# [title]: 标题
# [time]: 时间戳
# [date]: 日期

# 录制文件标题
[video]
name = "[rid]-[title]-[date]-[time]"

# 录制文件标题
[danmu]
name = "[rid]-[title]-[date]-[time]"

# 各平台cookie
[cookie.bili]
cookie = "xxxx"
user-agent = "xxxx"

[cookie.huya]
cookie = "xxxx"
user-agent = "xxxx"
