[package]
name = "seam"
version = "0.1.18"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seam_core = { path = "../seam_core" }
seam_danmu = { path = "../seam_danmu" }
seam_status = { path = "../seam_status" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
paste = "1.0"
