name: Build GUI Release

permissions:
  contents: write

on:
  push:
    tags:
      - v_gui.*

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changelog_reader.outputs.changes }}
      version: ${{ steps.changelog_reader.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Get version number
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION/v_gui./}
          echo "::set-output name=version::$VERSION"
      - name: Changelog Reader
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.2
        with:
          path: './crates/cli/CHANGELOG.md'
          version: ${{ steps.get_version.outputs.version }}

  build_seam:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'crates/gui/yarn.lock'
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: |
          cd crates/gui
          yarn install --frozen-lockfile
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: 'crates/gui'
          tagName: '${{github.ref_name}}'
          releaseName: 'Seam GUI ${{ needs.create_release.outputs.version }}'
          releaseBody: '${{ needs.create_release.outputs.changes }}'
          releaseDraft: false
          prerelease: false
